server:
  port: 8990

spring:
  application:
    name: dubbo-provider

dubbo:
  scan:
    base-packages: com.itdom
  protocol:
    port: 9000
    name: dubbo
  registry:
    address: zookeeper://192.168.150.49:2181
demo:
  service:
    version: 1.0.0
